### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by Erik-E-Christensen** [D-Multi/Midnight-Man#2]
Hello, this is dude2093350 CEO of cTechstudios, LLC. I believe this game has great potential (ps @dguis 3.00/2.99 in business terms is a marketing tactic, surprisingly afective) I would like you to know that I am willing to support you and am talking to my team about an acquisition, thank you. (This is NOT a formal acquisition notice or offer)

-dude2093350 cTechstudios, LLC CEO and president (This is an official statement)

**Comment by Erik-E-Christensen** [comment]
Actually according to your plan, this is not an RPG. An RPG would be like legend of Zelda and D&D series, this is more of a strategy/action game. Thanks

**Comment by dguisti** [comment]
Actually, you are going to go through the story line of fighting different enemies. Also, is cTechstudios officially a company now?

**Comment by Erik-E-Christensen** [comment]
cTechstudios will be represented as a legal entity in 2019 at an unknown time. We are aiming for the 3rd fiscal quarter. Also, even though you will be fighting enemies it is still a strategy/action game, that is of course, unless the game is more procedural and has an actual story line, not just an infinite loop like you said.

**Comment by Erik-E-Christensen** [comment]
(at least hopefully in 2019)
