### ISSUE TITLE
Official Plan

### ISSUE THREAD

**Issue by Erik-E-Christensen** [D-Multi/Midnight-Man#3]
Hello again, my team and I have decided we like your game and would like to make a deal with you since this is a public place we can not discuss the deal here. Yes, you would get paid in exchange for giving some rights of the game to cTechstudios, LLC. cTechstudios, LLC would like some changes to be made, however to this initial plan and would like to become the publisher. Thank You. (We will contact you with the full deal @dguis  @L8555 at the D-Multi website contact form or the Support email.

-dude2093350 Founder, CEO, President
cTechstudios, LLC.

**Comment by Erik-E-Christensen** [comment]
it is at dude2093350.github.io/cTech/legal.html/Agreement.docx, I contacted you with the access code at your Email, thanks.

**Comment by dguisti** [comment]
Sorry! I feel that we should wait until the game is a little more developed before we decide to accept your offer. We will keep your offer in mind, and get back to you as soon as we can. Thanks!

<a href="https://github.com/D-Multi"><h6>Officially written as a representative of D-Multi</h6><img src="https://dguis.github.io/RES/New%20Logos/DM50x50db.png"></a>

**Comment by Erik-E-Christensen** [comment]
Have you reveiwed the offer?

**Comment by Erik-E-Christensen** [comment]
At the website?
We are willing to negotiate.

**Comment by dguisti** [comment]
I have reviewed the offer, but I feel that we are not very far along at all and would like some time before making any deals.

**Comment by Erik-E-Christensen** [comment]
Deals will be harder to make after/during development and it is best to start early
However we understand and will leave you alone now, will contact you later

**Comment by dguisti** [comment]
We would prefer to keep the project to are selves. We believe that it will be of greater advantage to us to keep all of the profits and publish the game ourselves, as that process would not be very expensive. Also, we expect to make much more money than $50 USD, so this offer would not be the best possible option for us. We thank you for your offer, and kindly decline.

<a href="https://github.com/D-Multi"><h6>Officially Written by D-Multi</h6><img src="https://dguis.github.io/RES/New%20Logos/DM50x50db.png"></a>
