### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Erik-E-Christensen** [D-Multi/Midnight-Man#4]
I request to be set as a contributer, thanks you

**Comment by dguisti** [comment]
I have to make sure my friend approves. @maxthecoder do you approve?

**Comment by Erik-E-Christensen** [comment]
If you don't mind my asking of such, would I know @maxthecoder ?

**Comment by dguisti** [comment]
No. He is a friend from my school.

**Comment by Erik-E-Christensen** [comment]
Also are you using GameMaker?

**Comment by Erik-E-Christensen** [comment]
Or unity3d

**Comment by Erik-E-Christensen** [comment]
Or UNREAL

**Comment by Erik-E-Christensen** [comment]
Or CRYengine

**Comment by Erik-E-Christensen** [comment]
Or SlipSpace, yep I think I named them all!

**Comment by dguisti** [comment]
We are using GameMaker 1.4.
