### ISSUE TITLE
Trademark

### ISSUE THREAD

**Issue by Erik-E-Christensen** [D-Multi/Midnight-Man#8]
I regret to inform you that midnight man is a registered trademark if MidnighMan, LLC a cigerette company in west virginia

**Comment by Erik-E-Christensen** [comment]
http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4803:rjvkt1.2.2

**Comment by Erik-E-Christensen** [comment]
Also cTechstudios is announcing a partnership with Ezra Gaming Group to bring a new franchise WorldofWar and The Fulton Game. We just thought @dguis would want to know.

**Comment by dguisti** [comment]
The Fulton Game sounds like it would be pretty close to Civilization, but if you say so.

**Comment by dguisti** [comment]
Also, that mark is for the MM logo, not for the name Midnight Man.

**Comment by maxsruda** [comment]
I also believe that "The Midnight Man" is a 2016 horror film.
